Ebola (2014)
========================================================

Références
----------

- Notice en français de l'OMS: http://www.who.int/mediacentre/factsheets/fs103/fr/
- suivi épidémie par l'[OMS](http://who.int/csr/don/archive/disease/ebola/en/)

- Page du [Ministere de la santé Sierra Leone](http://www.mohsw.gov.lr/documents/Liberia%20EVD%20epidemic%20sitrep-%20on%2039-%2022-06-14.pdf%20docx.pdf)

The Sierra Leone Ministry of Health & Sanitation has a [Facebook page at](https://www.facebook.com/pages/Ministry-of-Health-and-Sanitation-Sierra-Leone/281064805403702)

A photo of the [EU Mobile lab in Guinea](http://ec.europa.eu/echo/images/photos/news/2014/20140411.jpg)

[Estimating the Future Number of Cases in the Ebola Epidemic — Liberia and Sierra Leone, 2014–2015](http://www.cdc.gov/mmwr/preview/mmwrhtml/su6303a1.htm?s_cid=su6303a1_w#Appendix-tab1)


Cartographie dynamique [Healthmap](http://healthmap.org/ebola/#timeline)

[Ebola Outbreak 2014: Information Resources](http://disasterinfo.nlm.nih.gov/dimrc/ebola_2014.html?utm_source=NHC+Master+List&utm_campaign=61d2a02fdf-DR633&utm_medium=email&utm_term=0_dabc309806-61d2a02fdf-54391422)

[site français](http://www.les-crises.fr/virus-ebola/)

World Health
Organization developed the Field Information Management System (FIMS) software.
The FIMSis a tool developed to support outbreak response activities in terms of case and contact data collection, analysis
and production of related reports.FIMSsupports the following aspects of case and contact data management:
- Registration of cases and case related data;
- Registration of contacts and contacts related data;
- Production of daily follow up reports;
- Production of predefined summary and detailed reports
- Exporting of data to different formats (txt, xls, xml etc.) for further analysis;
- Summary case and contact mapping (using Health Mapper or GIS softwares);
- Visualization of chains of transmission;

Contexte général
----------------

- frontière avec le Mali (troupes françaises)
- frontières avec Mauritanie, Sierra Leone, Liberia
- pays riche en minerai (minerai de fer. Le pays est également le premier exportateur mondial de bauxite, la matière première utilisée dans la production d'aluminium, et possède de riches gisements d'or. ) => expatriés.
- un cas suspect au Nigeria, en fait dengue haemorrhagic fever transmission par moustique

Date: 3 Apr 2014
----------------
Source: WHO Global Alert and Response (GAR), Disease Outbreak News < http://www.who.int/csr/don/2014_04_ebola/en > 

L'OMS appuie les autorités nationales dans la réponse à une emergence de la maladie à virus Ebola (EVD, anciennement connu sous le nom d'Ebola fièvre hémorragique). L'épidémie est maintenant confirmé comme etant causée par une souche de virus Ebola avec très proche homologie (98 pour cent) à la Ebola Zaïre. C'est la 1ère fois que la maladie a été détectée en Afrique de l'Ouest. Des cas ont été signalés dans le 1er zones boisées sud-Guinée. L'épidémie a rapidement évolué, et plusieurs districts et Conakry ont signalé des cas et des décès causés par EVD. Un petit nombre de cas et les décès suspects ont également été signalés dans les pays voisins avec chacun d'eux ayant traversé de la Guinée.
Les cas confirmés ont été signalés en Guinée et au Libéria. (Lire la suite
à la source URL). 

#### Filovirus

La famille des filoviridae (filovirus) est composée de 3 genres:
- Ebolarirus
- Marburgvirus
- Cuevavirus
Le genre **ebolavirus** est composé de **5** espèces:
- Bundibugyo ebolavirus (BDBV)
- Zaire ebolavirus (EBOV)
- Reston ebolavirus (RESTV)
- Sudan ebolavirus (SUDV)
- Taï Forest ebolavirus (TAFV)

BDBV, EBOV, et SUDV sont fréquemment retrouvés dans des épidémies importantes.

#### Source: Business Standard, Inde [modifié]
< http://www.business-standard.com/article/news-ians/ebola-toll-rises-to-84-in-guinea-114040300723_1.html >


Les autorités sanitaires de la Guinée jeudi [3 avril 2014] déclarent 4 nouveaux cas de maladie du virus Ebola ont été signalés dans le pays, ce qui porte le nombre total de patients à **134**, dont **84** ont succombé à la maladie virale. La maladie est surtout répandue dans le sud villes régionales de Guéckédou, Macenta, Kissidougou et la capitale Conakry, a rapporté Xinhua.

Pour freiner la propagation de l'épidémie, le gouvernement a pris certaines mesures qui comprennent la création de centres d'isolement médical dans le régions touchées et la désinfection des maisons avec des cas suspects ou où les patients atteints de la maladie d'Ebola sont morts. Le gouvernement a également mobilisation entrepris des ressources nécessaires pour fournir individu matériaux de protection aux zones les plus touchées. L'UNICEF a également procédé à la distribution de kits d'hygiène pour écoles dans les zones les plus touchées par le virus. 

#### Source: OMS / AFRO EPR - Foyer Nouvelles [modifié]
< http://www.afro.who.int/en/clusters-a-programmes/dpc/epidemic-a-pandemic-alert-and-response/outbreak-news.html >


Comme COMPTER DU 1ER AVRIL 2014, le ministère de la Santé de Guinée a rapporté une
total cumulé de 127 cas cliniquement compatibles de EVD, dont
35 sont confirmés en laboratoire par PCR. Le nombre total comprend 83
décès (CRF 65 pour cent). Ces chiffres correspondent à 5 nouvelle clinique
cas et 3 nouveaux décès depuis la dernière mise à jour le 31 mars 2014; 22
patients restent dans l'isolement.

Les chiffres actuels de cas cliniques selon le lieu de rapport sont les suivants:

- Conakry (12 cas, dont 4 décès),
- Guekedou (79 cases/57 décès),
- Macenta (23 cases/14 décès),
- Kissidougou (9 cas / 5 décès), et
- Dabola et Djingaraye combinés (4 cas / 3 décès).

11 des cas à Conakry ont été confirmés en laboratoire du virus Ebola
maladie virale (EVD); 14 travailleurs de la santé ont également été laboratoire
confirmé pour EVD, dont 8 sont morts. enquêtes sur les cas et contacts
suivi se poursuivent, avec 375 contacts sous suivi médical à
présente. 

FAQ Ebola
----------
[CDC](Interim Guidance for Environmental Infection Control in Hospitals for Ebola Virus)

Allemagne
==========

- 7 hôpitaux spécialisés pour la prise en charge de malade hautement contagieux: Leipzig (St. Georg Clinic ), Hambourg (UK  Hamburg-Eppendorf), Frankfurt am Main (UK), 

patients rappatriés
-------------------
- 1 Hambourg: sénégalais travaillant pour l'OMS, contaminé en Sierra Leone. Hospitalisé fin aout, déclaré guéri le 4/10/2014
- [2014-10-02] Frankfurt am Main: médecin Ougandais travaillant pour l'OMS et contaminé en Sierra Leone
- [2014-10-09] Soudanais infecté au Libéria

sources
-------
[Third Ebola patient arrives in Germany from Africa](http://www.dw.de/third-ebola-patient-arrives-in-germany-from-africa/a-17983734)
[Frankfurt ready to treat Ebola patient](http://www.dw.de/frankfurt-ready-to-treat-ebola-patient/a-17971270)
[German doctors release cured Ebola patient](http://www.dw.de/german-doctors-release-cured-ebola-patient/a-17973760)


USA
===

A patient being treated for Ebola has died in the hospital in the US state of Texas. He flew to the US from Liberia on September 20, at first showing no symptoms, and was kept in an isolation unit in a hospital in Dallas after September 28. Décède le 8/10/2014.

[Liberian Ebola patient dies in Texas hospital](http://www.dw.de/liberian-ebola-patient-dies-in-texas-hospital/a-1798300)

[Family members of Dallas Ebola patient confined to home under armed guard ](http://www.dallasnews.com/news/metro/20141002-family-members-of-dallas-ebola-patient-confined-to-home-under-armed-guard.ece)

[IDE pas pretes](http://www.nationalnursesunited.org/press/entry/national-nurse-survey-shows-hospitals-still-not-prepared-for-us-ebola)


Esapagne
========

patients rappatriés
-------------------
- 1
- 2

Patients contaminés
-------------------
- IDE/AS qui s'est occupée du patient rappatrié 2. Institudo de salud carlos III.

[Europe probes Spanish Ebola transmission](http://www.dw.de/europe-probes-spanish-ebola-transmission/a-17981652)


Open Street Map
===============

[Online volunteers map uncharted Ebola zones to help save lives](http://www.trust.org/item/20140918050913-ho2mk/?source=spotlight)

