---
title: "EVB par pays"
author: "JcB"
date: "10/07/2014"
output: html_document
---

Suivi de l'épidémie de fièvre EBOLA en 2014
===========================================

source: [promed mail](http://www.promedmail.org) et [OMS](http://who.int/csr/don/2014_07_15_ebola/en/)

Les données sont colligées dans __EVB_PromedMail.ods__ puis réenregistrées au format .csv dans __EVB_pays.csv__.

```{r init}
library(knitr)
library(xts)

file <- "EVB_pays.csv"
d <- read.csv(file, header = TRUE)
d$Date <- as.Date(d$Date)
names(d)
str(d)
```

```{r calculs}
sum(d$Total[d$Date == max(d$Date)])
sum(d$Death[d$Date == max(d$Date)])
dcd <- sum(d$Death[d$Date == max(d$Date)])
cas <- sum(d$Total[d$Date == max(d$Date)])
cfr <- round(dcd * 100 / cas, 2)
cas.g <- d$Total[d$Pays == "Guinea" & d$Date == max(d$Date)]
dcd.g <- d$Death[d$Pays == "Guinea" & d$Date == max(d$Date)]
cfr.g <- round(dcd.g * 100 / cas.g, 2)
cas.sl <- d$Total[d$Pays == "Sierra Leone" & d$Date == max(d$Date)]
dcd.sl <- d$Death[d$Pays == "Sierra Leone" & d$Date == max(d$Date)]
cfr.sl <- round(dcd.sl * 100 / cas.sl, 2)
cas.lb <- d$Total[d$Pays == "Liberia" & d$Date == max(d$Date)]
dcd.lb <- d$Death[d$Pays == "Liberia" & d$Date == max(d$Date)]
cfr.lb <- round(dcd.lb * 100 / cas.lb, 2)

a <- cbind(cas, cas.g, cas.sl, cas.lb)
b <- cbind(dcd, dcd.g, dcd.sl, dcd.lb)
t <- rbind(a,b)
colnames(t) <- c("Total", "Guinée", "Sierra Leone", "Libéria")
rownames(t) <- c("cas", "Décès")
kable(t)

x <- xts(d, order.by = d$Date)
plot(x$Total[x$Pays == "Guinea"])
barplot(x$Total[x$Pays == "Guinea"])

# major.format permet de définir la syntaxe des dates pour l'axe des X [source](https://stat.ethz.ch/pipermail/r-help/2011-July/285360.html)
m <- par("mar")
par(mar = c(6.1, 4.1, 4.1, 2.1))
plot(x$Total[x$Pays == "Guinea"], ylim=c(0,450), type = "bars", main = "Nombre cumulé de cas d'Ebola", ylab="nombre de cas", las = 2, cex.axis = 0.7, major.format="%d/%m/%Y")
lines(x$Total[x$Pays == "Guinea"], ylim=c(0,450), col="red")
lines(x$Total[x$Pays == "Liberia"], ylim=c(0,450), col="blue")
lines(x$Total[x$Pays == "Sierra Leone"], ylim=c(0,450), col="green")
legend("topleft", legend = c("Guinée","Libéria","Sierra Leone"), col=c("red","blue","green"), lty=1, lwd=2)
par(mar=m)

tapply(d$Total, d$Date, sum)
tapply(d$Death, d$Date, sum)

```
Dernier bilan: `r max(d$Date)`  
Nombre cumulé de cas: $`r cas`$  
Nombre cumulé de décès: $`r dcd`$  
Mortalité: $`r cfr`$ % 

New Cases et Courbe épidémique
==============================

```{r newcase}
library(epitools)
file <- "newcases.csv"
n <- read.csv(file, header = TRUE)
n$date <- as.Date(n$date)
# On crée autant d'enregistrements qu'il y a de cas
x.date <- rep(n$date, n$new.case)
x.pays <- rep(n$pays, n$new.case)
new.case <- data.frame(x.date, x.pays)

epicurve.weeks(x.date, sunday = FALSE, main="Ebola - Nouveaux cas")

col3seq.d <- c("#43A2CA", "#A8DDB5", "#E0F3DB")
ebola <- epicurve.weeks(new.case$x.date, sunday = FALSE, strata = new.case$x.pays, col = col3seq.d, legend=TRUE, axisnames = FALSE)
axis(1, at = ebola$xvals, labels = ebola$cweek, tick = FALSE, line = 0)
axis(1, at = ebola$xvals, labels = ebola$cmonth, tick = FALSE, line = 1)
title(main="Ebola - Nouveaux cas", ylab = "fréquence", xlab = "2014 - semaines")
```
legend("topleft", legend=c("Sierra Leone", "Libéria","Guinée"), col=col3seq.d, lty=2)

